#pragma once
#include "NativeGameplayTags.h"
namespace SteppeTags
{
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_State_Roaming);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_State_Alert);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_State_Yielding);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_State_Flee);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_State_Recovering);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_State_Idle);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_State_Moving);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_State_Stumbling);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_State_Falling);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_Gait_Idle);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_Gait_Walk);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_Gait_Trot);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_Gait_Canter);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_Gait_Gallop);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Horse_Gait_Sprint);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rider_State_OnFoot);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rider_State_Mounting);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rider_State_Mounted);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rider_State_Dismounting);
    STEPPE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rider_State_Falling);
}
