#include "Core/SteppeGameplayTags.h"
namespace SteppeTags
{
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Roaming, "Horse.State.Roaming");
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Alert, "Horse.State.Alert");
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Yielding, "Horse.State.Yielding");
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Flee, "Horse.State.Flee");
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Recovering, "Horse.State.Recovering");
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Lassoed, "Horse.State.Lassoed");
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Captured, "Horse.State.Captured");
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Idle, "Horse.State.Idle");
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Moving, "Horse.State.Moving");
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Stumbling, "Horse.State.Stumbling");
    UE_DEFINE_GAMEPLAY_TAG(Horse_State_Falling, "Horse.State.Falling");
    UE_DEFINE_GAMEPLAY_TAG(Horse_Gait_Idle, "Horse.Gait.Idle");
    UE_DEFINE_GAMEPLAY_TAG(Horse_Gait_Walk, "Horse.Gait.Walk");
    UE_DEFINE_GAMEPLAY_TAG(Horse_Gait_Trot, "Horse.Gait.Trot");
    UE_DEFINE_GAMEPLAY_TAG(Horse_Gait_Canter, "Horse.Gait.Canter");
    UE_DEFINE_GAMEPLAY_TAG(Horse_Gait_Gallop, "Horse.Gait.Gallop");
    UE_DEFINE_GAMEPLAY_TAG(Horse_Gait_Sprint, "Horse.Gait.Sprint");
    UE_DEFINE_GAMEPLAY_TAG(Rider_State_OnFoot, "Rider.State.OnFoot");
    UE_DEFINE_GAMEPLAY_TAG(Rider_State_Mounting, "Rider.State.Mounting");
    UE_DEFINE_GAMEPLAY_TAG(Rider_State_Mounted, "Rider.State.Mounted");
    UE_DEFINE_GAMEPLAY_TAG(Rider_State_Dismounting, "Rider.State.Dismounting");
    UE_DEFINE_GAMEPLAY_TAG(Rider_State_Falling, "Rider.State.Falling");
    UE_DEFINE_GAMEPLAY_TAG(Rider_State_BalanceWarning, "Rider.State.BalanceWarning");
    UE_DEFINE_GAMEPLAY_TAG(Rider_State_Dragged, "Rider.State.Dragged");
    UE_DEFINE_GAMEPLAY_TAG(Rider_State_Recovering, "Rider.State.Recovering");
    UE_DEFINE_GAMEPLAY_TAG(Lasso_State_Stored, "Lasso.State.Stored");
    UE_DEFINE_GAMEPLAY_TAG(Lasso_State_Aiming, "Lasso.State.Aiming");
    UE_DEFINE_GAMEPLAY_TAG(Lasso_State_Thrown, "Lasso.State.Thrown");
    UE_DEFINE_GAMEPLAY_TAG(Lasso_State_Attached, "Lasso.State.Attached");
    UE_DEFINE_GAMEPLAY_TAG(Lasso_State_Recovering, "Lasso.State.Recovering");
    UE_DEFINE_GAMEPLAY_TAG(Lasso_State_Subdued, "Lasso.State.Subdued");
    UE_DEFINE_GAMEPLAY_TAG(Lasso_State_Captured, "Lasso.State.Captured");
}
